import type { Review } from "@/lib/types";

const DAY = 86_400_000;

function daysAgo(days: number): string {
  return new Date(Date.now() - days * DAY).toISOString();
}

export function getDemoReviews(): Review[] {
  return [
    {
      id: "android-demo-1",
      store: "google_play",
      platform: "android",
      rating: 1,
      title: "Ads after every tap",
      body: "The app is useful but an ad appears after almost every action. It is unusable now.",
      language: "en",
      territory: "USA",
      appVersion: "6.4.0",
      createdAt: daysAgo(1),
      dateSemantics: "created_at",
      source: "demo",
    },
    {
      id: "ios-demo-1",
      store: "apple_app_store",
      platform: "ios",
      rating: 5,
      title: "Exactly what I needed",
      body: "Clean, fast, and the new insights screen saves me a lot of time.",
      language: "en",
      territory: "USA",
      appVersion: "6.4.0",
      createdAt: daysAgo(2),
      dateSemantics: "created_at",
      source: "demo",
    },
    {
      id: "android-demo-2",
      store: "google_play",
      platform: "android",
      rating: 2,
      title: "Keeps crashing",
      body: "It crashes whenever I open the reports tab since the latest update.",
      language: "en",
      territory: "GBR",
      appVersion: "6.4.0",
      createdAt: daysAgo(3),
      dateSemantics: "created_at",
      source: "demo",
    },
    {
      id: "ios-demo-2",
      store: "apple_app_store",
      platform: "ios",
      rating: 4,
      title: "Great app, missing one thing",
      body: "Really easy to use. Please add a weekly export option.",
      language: "en",
      territory: "CAN",
      appVersion: "6.3.2",
      createdAt: daysAgo(4),
      dateSemantics: "created_at",
      source: "demo",
    },
    {
      id: "android-demo-3",
      store: "google_play",
      platform: "android",
      rating: 3,
      title: "Fine overall",
      body: "The core features work, but loading the dashboard takes too long.",
      language: "en",
      territory: "AUS",
      appVersion: "6.3.2",
      createdAt: daysAgo(6),
      dateSemantics: "created_at",
      source: "demo",
    },
    {
      id: "ios-demo-3",
      store: "apple_app_store",
      platform: "ios",
      rating: 1,
      title: "Subscription issue",
      body: "I was charged after cancelling and support has not replied.",
      language: "en",
      territory: "USA",
      appVersion: "6.3.1",
      createdAt: daysAgo(8),
      dateSemantics: "created_at",
      source: "demo",
    },
    {
      id: "android-demo-4",
      store: "google_play",
      platform: "android",
      rating: 5,
      title: "Super useful",
      body: "Love the redesign. Everything is faster and easier to find.",
      language: "en",
      territory: "DEU",
      appVersion: "6.3.1",
      createdAt: daysAgo(10),
      dateSemantics: "created_at",
      source: "demo",
    },
    {
      id: "ios-demo-4",
      store: "apple_app_store",
      platform: "ios",
      rating: 2,
      title: "Login loop",
      body: "Every time I open the app it logs me out and asks for verification again.",
      language: "en",
      territory: "ARG",
      appVersion: "6.3.0",
      createdAt: daysAgo(12),
      dateSemantics: "created_at",
      source: "demo",
    },
    {
      id: "android-demo-5",
      store: "google_play",
      platform: "android",
      rating: 4,
      title: "Good value",
      body: "The free version is generous and the premium price is reasonable.",
      language: "en",
      territory: "BRA",
      appVersion: "6.3.0",
      createdAt: daysAgo(14),
      dateSemantics: "created_at",
      source: "demo",
    },
    {
      id: "ios-demo-5",
      store: "apple_app_store",
      platform: "ios",
      rating: 3,
      title: "Mixed after update",
      body: "The new design looks better, but two features I used are gone.",
      language: "en",
      territory: "ESP",
      appVersion: "6.3.0",
      createdAt: daysAgo(17),
      dateSemantics: "created_at",
      source: "demo",
    },
    {
      id: "android-demo-6",
      store: "google_play",
      platform: "android",
      rating: 1,
      title: "Does not work on my phone",
      body: "The screen stays blank on Android 15 after installing.",
      language: "en",
      territory: "IND",
      appVersion: "6.2.8",
      createdAt: daysAgo(20),
      dateSemantics: "created_at",
      source: "demo",
    },
    {
      id: "ios-demo-6",
      store: "apple_app_store",
      platform: "ios",
      rating: 5,
      title: "Best in the category",
      body: "Reliable, thoughtfully designed, and the content keeps improving.",
      language: "en",
      territory: "JPN",
      appVersion: "6.2.8",
      createdAt: daysAgo(24),
      dateSemantics: "created_at",
      source: "demo",
    },
  ];
}
